# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CameraQuality' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CameraQuality
  pod 'TesseractOCRiOS', '4.0.0'


  target 'CameraQualityTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CameraQualityUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
