# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AVCamera' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AVCamera


  # CIRectangleFeature
  pod "Rectangle", :git => 'https://github.com/ThePowerOfSwift/Rectangle.git'


  target 'AVCameraTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AVCameraUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
